[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial Monitor Options
monitor_speed = 115200

; Library Dependencies (Add Edge Impulse here later)
lib_deps =
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.14
    arduino-libraries/NTPClient @ ^3.2.1
    bblanchon/ArduinoJson @ ^7.0.4
    adafruit/Adafruit MLX90640 @ ^1.0.2
    kosme/arduinoFFT @ ^2.0.2

; Build Flags (Enable PSRAM if needed)
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
