[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial Monitor Options
monitor_speed = 115200

; Library Dependencies (Add Edge Impulse here later)
lib_deps =
    ; knolleary/PubSubClient @ ^2.8 (For MQTT/Firebase later)

; Build Flags (Enable PSRAM if needed)
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
